// <auto-generated />
using System;
using CodeFirstProj.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstDAL.Migrations
{
    [DbContext(typeof(ProjDbContext))]
    [Migration("20210830100545_Emp Loc Dept")]
    partial class EmpLocDept
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CodeFirstProj.Models.Dept", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationLid")
                        .HasColumnType("int");

                    b.HasKey("Did");

                    b.HasIndex("LocationLid");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("CodeFirstProj.Models.Employee", b =>
                {
                    b.Property<int>("Eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DeptDid")
                        .HasColumnType("int");

                    b.Property<int>("Did")
                        .HasColumnType("int");

                    b.Property<string>("Ename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Esal")
                        .HasColumnType("int");

                    b.HasKey("Eid");

                    b.HasIndex("DeptDid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CodeFirstProj.Models.Location", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Lname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lid");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CodeFirstProj.Models.Dept", b =>
                {
                    b.HasOne("CodeFirstProj.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationLid");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CodeFirstProj.Models.Employee", b =>
                {
                    b.HasOne("CodeFirstProj.Models.Dept", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptDid");

                    b.Navigation("Dept");
                });
#pragma warning restore 612, 618
        }
    }
}
