//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public Nullable<int> d_id { get; set; }
        public Nullable<int> sal { get; set; }

        public override string ToString()
        {
            string info = $"-----------------------------\nID : {eid}\nName : {ename}\nDept ID : {d_id}\nSalary : {sal}\n-----------------------------";
            return info;
        }

    }
}
